"resources"
{
"materials/cs_havana/woodm.vmt" "file"
"materials/cs_havana/woodm.vtf" "file"
"materials/de_nuke/nuke_metalgrate_01.vmt" "file"
"materials/de_nuke/nuke_metalgrate_01.vtf" "file"
"materials/de_piranesi/pi_grnmetalt.vmt" "file"
"materials/de_piranesi/pi_grnmetalt.vtf" "file"
"materials/nature/infblendgrassdirt001a.vmt" "file"
"materials/nature/infblendgrassdirt001a.vtf" "file"
"materials/de_train/train_grass_floor_01.vmt" "file"
"materials/de_train/train_grass_floor_01.vtf" "file"
"materials/de_train/train_dirt_floor_01" "file"
"materials/de_train/train_dirt_floor_01" "file"
}
